#!/usr/bin/env python3
"""Pipeline health dashboard for Light Tower Insights."""

from __future__ import annotations
import json
from datetime import datetime, timezone, timedelta
from pathlib import Path
from typing import Any

SCRIPT_DIR = Path(__file__).parent
SITE_ROOT = SCRIPT_DIR.parent
STATE_DIR = SITE_ROOT / ".editorial-state"
RUNS_DIR = SITE_ROOT / "data" / "editorial_runs"
HEALTH_PATH = SITE_ROOT / "HEALTH.md"


def load_json(path: Path) -> Any:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None


def load_jsonl(path: Path) -> list[dict[str, Any]]:
    entries = []
    try:
        for line in path.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if line:
                try:
                    entries.append(json.loads(line))
                except json.JSONDecodeError:
                    pass
    except OSError:
        pass
    return entries


def source_health() -> str:
    source_path = STATE_DIR / "source-health.json"
    data = load_json(source_path)
    if not isinstance(data, dict):
        return "No source health data available"
    quarantined = data.get("quarantined", {})
    healthy = data.get("healthy_feeds", 0)
    if isinstance(quarantined, dict):
        quarantined_count = sum(1 for v in quarantined.values() if v)
    else:
        quarantined_count = len(quarantined) if isinstance(quarantined, list) else 0
    return f"{healthy} healthy, {quarantined_count} quarantined"


def pipeline_stats(days: int = 7) -> dict[str, Any]:
    cutoff = datetime.now(timezone.utc) - timedelta(days=days)
    runs = []
    if RUNS_DIR.exists():
        for path in sorted(RUNS_DIR.glob("*.json"), reverse=True):
            data = load_json(path)
            if not isinstance(data, dict):
                continue
            try:
                run_date = datetime.fromisoformat(str(data.get("run_at", "")[:10]) + "T00:00:00+00:00")
                if run_date >= cutoff:
                    runs.append(data)
            except (TypeError, ValueError):
                continue

    total = len(runs)
    success = [r for r in runs if r.get("articles")]
    total_articles = sum(len(r.get("articles", [])) for r in success)
    costs = sum(
        (r.get("pipeline_cost", {}).get("total", 0) if isinstance(r.get("pipeline_cost"), dict)
         else float(r.get("pipeline_cost", 0) or 0))
        for r in runs
    )
    return {
        "total_runs": total,
        "successful_runs": len(success),
        "total_articles": total_articles,
        "estimated_cost_30d": round(costs, 4),
    }


def provider_stats() -> str:
    log_path = STATE_DIR / "provider-log.jsonl"
    entries = load_jsonl(log_path)
    switches = [e for e in entries if e.get("reason")]
    if not switches:
        return "Primary (DeepSeek) — no fallback activations this period"
    last = switches[-1]
    return f"Last fallback: {last.get('timestamp','unknown')[:16]} — {last.get('reason','')}"


def main():
    src = source_health()
    pipe = pipeline_stats(7)
    prov = provider_stats()

    report = f"""# Light Tower Insights — Pipeline Health

**Last updated:** {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}

## Feeds
- {src}

## Pipeline (last 7 days)
- Runs: {pipe['total_runs']}
- Successful (published): {pipe['successful_runs']}
- Articles: {pipe['total_articles']}
- Est. LLM cost (30d): ${pipe['estimated_cost_30d']}

## LLM Provider
- {prov}

## Skip Log
- Check .editorial-state/skip-log.json for thin-news-day details.

---
*Auto-generated by scripts/health_report.py*
"""
    HEALTH_PATH.write_text(report, encoding="utf-8")
    print(f"Health report saved: {HEALTH_PATH.relative_to(SITE_ROOT)}")
    print(report)


if __name__ == "__main__":
    main()
