#!/usr/bin/env python3
"""
Light Tower Group PDF Carousel Pipeline (2026)

Master orchestration: Article → Strategy → Carousel Content → PDF

Input: Article from insights.json (generated by enhanced_prompts.py)
Output: Beautiful PDF carousel ready for LinkedIn

Flow:
1. Load article from insights.json
2. Run strategy selector (confirm carousel is best format)
3. Generate carousel content (Ben Rohr voice, slide copy)
4. Generate PDF carousel (premium design, 1080×1350px)
5. Save PDF to output directory
"""

from __future__ import annotations

import argparse
import html as html_lib
import json
import os
import re
import sys
from datetime import datetime
from pathlib import Path
from typing import Any

# Import pipeline components
sys.path.insert(0, str(Path(__file__).parent))

from social_strategy_selector import recommend_format
from carousel_content_writer import generate_carousel_content
from pdf_carousel_generator import CarouselPDFGenerator

SCRIPT_DIR = Path(__file__).parent
SITE_ROOT = SCRIPT_DIR.parent
INSIGHTS_JSON = SITE_ROOT / "insights.json"
INSIGHTS_DIR = SITE_ROOT / "insights"
PDF_OUTPUT_DIR = SITE_ROOT / "carousel_pdfs"

DEEPSEEK_API_KEY = os.environ.get("DEEPSEEK_API_KEY", "")

_env = SCRIPT_DIR / ".env"
if _env.exists():
    for _line in _env.read_text(encoding="utf-8").splitlines():
        if "=" in _line and not _line.startswith("#"):
            _k, _v = _line.split("=", 1)
            os.environ.setdefault(_k.strip(), _v.strip())

DEEPSEEK_API_KEY = os.environ.get("DEEPSEEK_API_KEY", DEEPSEEK_API_KEY)


def load_manifest() -> list[dict[str, Any]]:
    """Load insights manifest."""
    if not INSIGHTS_JSON.exists():
        return []
    return json.loads(INSIGHTS_JSON.read_text(encoding="utf-8"))


def select_article(slug: str | None = None) -> dict[str, Any]:
    """Select an article from manifest."""
    manifest = load_manifest()
    if not manifest:
        raise FileNotFoundError("No insights.json entries found")
    if slug:
        for article in manifest:
            if article.get("slug") == slug:
                return article
        raise ValueError(f"Slug not found: {slug}")
    return manifest[0]


def load_article_text(slug: str, article_data: dict[str, Any]) -> str:
    """Load article text from HTML or data."""
    html_path = INSIGHTS_DIR / f"{slug}.html"
    if html_path.exists():
        html = html_path.read_text(encoding="utf-8", errors="replace")
        match = re.search(
            r'<div\s+class="article-body"[^>]*>([\s\S]*?)</div>',
            html,
            flags=re.IGNORECASE,
        )
        article_html = match.group(1) if match else html
        article_html = re.sub(r"<script[\s\S]*?</script>", " ", article_html, flags=re.IGNORECASE)
        article_html = re.sub(r"<style[\s\S]*?</style>", " ", article_html, flags=re.IGNORECASE)
        text = re.sub(r"<[^>]+>", " ", article_html)
        text = html_lib.unescape(text)
        text = re.sub(r"\s+", " ", text)
        return text.strip()
    return article_data.get("body_text", "")


def run_pdf_pipeline(
    slug: str | None = None,
    dry_run: bool = False,
    verbose: bool = False,
    offline: bool = False,
) -> dict[str, Any]:
    """
    Run complete PDF carousel pipeline.

    Returns: Dict with pipeline results and PDF path
    """
    print("\n" + "=" * 80)
    print("LIGHT TOWER GROUP PDF CAROUSEL PIPELINE 2026")
    print("=" * 80)
    api_key = "" if offline else DEEPSEEK_API_KEY
    if offline:
        print("\nOffline/no-AI mode enabled. Using deterministic fallbacks only.")

    # Step 1: Load article
    print("\n[1/4] LOADING ARTICLE...")
    article = select_article(slug)
    slug = article.get("slug", "unknown")
    print(f"✓ Article: {article.get('title', 'Untitled')[:60]}")

    # Step 2: Strategy selector
    print("\n[2/4] ANALYZING STRATEGY...")
    article_text = load_article_text(slug, article)
    if not article_text:
        article_text = article.get("excerpt", "") or article.get("subtitle", "")

    try:
        strategy = recommend_format(article_text, article, api_key=api_key)
        print(f"✓ Format: {strategy.get('primary_format', 'carousel').upper()}")
        if strategy.get("primary_format") != "carousel":
            print(f"  [NOTE] Strategy recommends {strategy.get('primary_format')}. Using carousel anyway.")
    except Exception as e:
        print(f"[WARN] Strategy analysis failed: {e}")
        strategy = {"primary_format": "carousel"}

    # Step 3: Generate carousel content
    print("\n[3/4] GENERATING CAROUSEL CONTENT...")
    try:
        carousel_content = generate_carousel_content(article, article_text=article_text, api_key=api_key)
        num_slides = len(carousel_content.get("slides", []))
        print(f"✓ Generated {num_slides} slides")
        print(f"  Title: {carousel_content.get('carousel_title', 'Untitled')}")

        if verbose:
            print("\nSlide preview:")
            for i, slide in enumerate(carousel_content.get("slides", [])[:3], 1):
                print(f"  [{i}] {slide.get('eyebrow', '')} - {slide.get('headline', '')[:50]}")
            if num_slides > 3:
                print(f"  ... and {num_slides - 3} more")

    except Exception as e:
        print(f"[ERROR] Carousel content generation failed: {e}")
        sys.exit(1)

    # Step 4: Generate PDF
    print("\n[4/4] GENERATING PDF...")
    try:
        PDF_OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

        generator = CarouselPDFGenerator(output_dir=str(PDF_OUTPUT_DIR))
        pdf_path = generator.create_carousel_pdf(carousel_content)

        print(f"✓ PDF created: {pdf_path}")

    except Exception as e:
        print(f"[ERROR] PDF generation failed: {e}")
        sys.exit(1)

    # Summary
    print("\n" + "=" * 80)
    print("PIPELINE COMPLETE")
    print("=" * 80)
    print(f"Article: {article.get('title', 'Untitled')}")
    print(f"Strategy: {strategy.get('primary_format', 'carousel').upper()}")
    print(f"PDF Slides: {num_slides}")
    print(f"Output: {pdf_path}")
    print("\nReady to upload to LinkedIn.")
    print("=" * 80 + "\n")

    return {
        "article_slug": slug,
        "article_title": article.get("title", ""),
        "strategy": strategy,
        "carousel_content": carousel_content,
        "pdf_path": pdf_path,
        "generated_at": datetime.now().isoformat(),
        "offline": offline,
    }


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Light Tower Group PDF Carousel Pipeline",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python run_pdf_carousel_pipeline.py                    # Generate PDF for latest article
  python run_pdf_carousel_pipeline.py --slug tuscan-village-mixed-use-capital
  python run_pdf_carousel_pipeline.py --latest --verbose
        """,
    )
    parser.add_argument("--slug", help="Generate PDF for specific article")
    parser.add_argument("--latest", action="store_true", help="Generate for latest article")
    parser.add_argument("--verbose", action="store_true", help="Verbose output")
    parser.add_argument("--dry-run", action="store_true", help="Show output without saving")
    parser.add_argument("--offline", "--no-ai", action="store_true", help="Use deterministic fallbacks without calling external AI")

    args = parser.parse_args()

    try:
        result = run_pdf_pipeline(slug=args.slug, dry_run=args.dry_run, verbose=args.verbose, offline=args.offline)
        print(f"\n✓ Success: PDF carousel created at {result['pdf_path']}")

    except Exception as e:
        print(f"\n[ERROR] Pipeline failed: {e}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
